# Generated by Django 4.2.2 on 2024-01-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='temp_file'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_quote',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='temp_file'),
        ),
    ]
